#!/usr/bin/env python3
"""GeneMANIA task: export a cleaned first-page report PDF and matching PNG."""

from __future__ import annotations

import base64
import re
import shutil
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote

from pypdf import PdfReader, PdfWriter
from playwright.sync_api import Error as PlaywrightError
from playwright.sync_api import sync_playwright

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[4]))
    from protocol_gate import ProtocolGateError, infer_input_type, validate_protocol_ticket
    from webpages.genemania_org.search.common.io import safe_filename, write_json
else:
    from protocol_gate import ProtocolGateError, infer_input_type, validate_protocol_ticket
    from ..common.io import safe_filename, write_json


ROOT = Path(__file__).resolve().parents[5]
DEFAULT_HOMEPAGE = "https://genemania.org/"
DEFAULT_PAGE_ROOT = "https://genemania.org/link"
DEFAULT_JOB_ROOT = ROOT / "outputs" / "tasks"
DEFAULT_JOB_TAG = "GeneSetAnalysis_GeneMANIA"
PAGE_KEY = "genemania_org.search"
TASK_KEY = "gene_set_to_report_figure"
DEFAULT_ORGANISM_ID = "9606"
DEFAULT_LAYOUT = "circle"
DEFAULT_TOP_FUNCTIONS = 5
DEFAULT_PNG_DPI = 300
DEFAULT_VIEWPORT_WIDTH = 1500
DEFAULT_VIEWPORT_HEIGHT = 1600
DEFAULT_DEVICE_SCALE_FACTOR = 2
DEFAULT_HEADER_CROP_RATIO = 0.18
DEFAULT_FOOTER_CROP_RATIO = 0.08
DEFAULT_NETWORK_PNG_SCALE = 3

TASK_METADATA = {
    "task_key": TASK_KEY,
    "bio_category": "Gene set",
    "bio_goal": "Gene set -> GeneMANIA report figure",
    "provider": "GeneMANIA",
    "homepage": DEFAULT_HOMEPAGE,
    "interaction_mode": "browser_automation",
    "master_file_mode": "single_report_pdf",
}
REPORT_PDF_NAME = "genemania_report.pdf"
REPORT_PNG_NAME = "genemania_report.png"


class GeneMANIAError(RuntimeError):
    """Raised when the GeneMANIA webpage task cannot complete safely."""


def parse_args(argv: list[str] | None = None):
    import argparse

    parser = argparse.ArgumentParser(
        description="Export a cleaned first-page GeneMANIA report PDF and a matching PNG preview.",
    )
    parser.add_argument(
        "--gene",
        action="append",
        default=[],
        help="Gene symbol. Repeat the flag or pass comma/whitespace-separated values.",
    )
    parser.add_argument(
        "--job-dir",
        type=Path,
        help="Preferred output directory. Creates one clear task directory with final files and temp/.",
    )
    parser.add_argument(
        "--job-name",
        help="Optional label used to auto-build the job directory name.",
    )
    parser.add_argument(
        "--output-prefix",
        type=Path,
        help="Legacy output prefix. Writes <prefix>.genemania_report.pdf/.png/.summary.json/.errors.json.",
    )
    parser.add_argument(
        "--protocol-check-file",
        type=Path,
        help="Required protocol gate JSON generated by scripts/protocol_gate.py before a formal run.",
    )
    parser.add_argument(
        "--organism-id",
        default=DEFAULT_ORGANISM_ID,
        help=f"NCBI taxonomy id used in the GeneMANIA deep link URL (default: {DEFAULT_ORGANISM_ID}).",
    )
    parser.add_argument(
        "--top-functions",
        type=int,
        default=DEFAULT_TOP_FUNCTIONS,
        help=f"Number of enriched functions to color on nodes (default: {DEFAULT_TOP_FUNCTIONS}).",
    )
    parser.add_argument(
        "--layout",
        choices=["circle", "force", "linear"],
        default=DEFAULT_LAYOUT,
        help=f"Graph layout to apply before export (default: {DEFAULT_LAYOUT}).",
    )
    parser.add_argument(
        "--browser",
        default="",
        help="Optional path to a Chromium-family browser executable. Defaults to Playwright Chromium.",
    )
    parser.add_argument(
        "--png-dpi",
        type=int,
        default=DEFAULT_PNG_DPI,
        help=f"PNG render DPI for the cleaned first-page report preview (default: {DEFAULT_PNG_DPI}).",
    )
    return parser.parse_args(argv)


def split_arg_values(values: list[str]) -> list[str]:
    items: list[str] = []
    for raw_value in values:
        for piece in re.split(r"[\s,]+", raw_value):
            value = piece.strip()
            if value:
                items.append(value)
    return items


def load_genes(args: Any) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []

    for value in split_arg_values(args.gene):
        key = value.casefold()
        if key in seen:
            continue
        seen.add(key)
        ordered.append(value)
    return ordered


def build_query_url(organism_id: str, genes: list[str]) -> str:
    gene_part = quote("|".join(genes), safe="")
    return f"{DEFAULT_PAGE_ROOT}?o={quote(organism_id, safe='')}&g={gene_part}"


def derive_job_name(args: Any, genes: list[str]) -> str:
    if args.job_name:
        return safe_filename(args.job_name)
    return "_".join(safe_filename(gene) for gene in genes)


def _prefix_output_path(prefix: Path, suffix: str) -> Path:
    return prefix.parent / f"{prefix.name}{suffix}"


def build_output_layout(*, args: Any, genes: list[str]) -> dict[str, Path | str | None]:
    if args.job_dir and args.output_prefix:
        raise GeneMANIAError("Use either --job-dir or --output-prefix, not both.")

    if args.output_prefix:
        return {
            "mode": "legacy_prefix",
            "job_dir": None,
            "temp_dir": _prefix_output_path(args.output_prefix, ".temp"),
            "report_pdf_path": _prefix_output_path(args.output_prefix, ".genemania_report.pdf"),
            "report_png_path": _prefix_output_path(args.output_prefix, ".genemania_report.png"),
            "summary_path": _prefix_output_path(args.output_prefix, ".summary.json"),
            "errors_path": _prefix_output_path(args.output_prefix, ".errors.json"),
        }

    job_dir = args.job_dir or (DEFAULT_JOB_ROOT / f"{DEFAULT_JOB_TAG}_{derive_job_name(args, genes)}")
    temp_dir = job_dir / "temp"
    return {
        "mode": "job_dir",
        "job_dir": job_dir,
        "temp_dir": temp_dir,
        "report_pdf_path": job_dir / REPORT_PDF_NAME,
        "report_png_path": job_dir / REPORT_PNG_NAME,
        "summary_path": temp_dir / "summary.json",
        "errors_path": temp_dir / "errors.json",
    }


def copy_input_artifacts(*, genes: list[str], temp_dir: Path | None) -> dict[str, str]:
    metadata = {
        "normalized_input_file": "",
        "raw_report_pdf": "",
        "raw_network_png": "",
    }
    if temp_dir is None:
        return metadata

    temp_dir.mkdir(parents=True, exist_ok=True)
    normalized_input_path = temp_dir / "normalized_input_genes.txt"
    normalized_input_path.write_text("\n".join(genes) + "\n", encoding="utf-8")
    metadata["normalized_input_file"] = str(normalized_input_path)
    metadata["raw_report_pdf"] = str(temp_dir / "raw_report.pdf")
    metadata["raw_network_png"] = str(temp_dir / "network_debug.png")
    return metadata


def resolve_browser_executable(user_path: str) -> str | None:
    if not user_path:
        return None
    resolved = Path(user_path).expanduser().resolve()
    if not resolved.exists():
        raise GeneMANIAError(f"Browser not found: {resolved}")
    return str(resolved)


def crop_pdf_first_page(
    input_pdf: Path,
    output_pdf: Path,
    *,
    header_ratio: float = DEFAULT_HEADER_CROP_RATIO,
    footer_ratio: float = DEFAULT_FOOTER_CROP_RATIO,
) -> dict[str, float]:
    reader = PdfReader(str(input_pdf))
    if len(reader.pages) == 0:
        raise GeneMANIAError(f"PDF has no pages: {input_pdf}")

    page = reader.pages[0]
    width = float(page.mediabox.width)
    height = float(page.mediabox.height)
    header_crop = height * header_ratio
    footer_crop = height * footer_ratio
    if header_crop + footer_crop >= height:
        raise GeneMANIAError(
            f"Crop ratios are too aggressive for page height {height}: header={header_ratio}, footer={footer_ratio}."
        )

    new_bottom = footer_crop
    new_top = height - header_crop
    page.cropbox.lower_left = (0, new_bottom)
    page.cropbox.upper_right = (width, new_top)
    page.mediabox.lower_left = (0, new_bottom)
    page.mediabox.upper_right = (width, new_top)

    writer = PdfWriter()
    writer.add_page(page)
    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    with output_pdf.open("wb") as handle:
        writer.write(handle)

    return {
        "original_width_pt": width,
        "original_height_pt": height,
        "header_crop_ratio": header_ratio,
        "footer_crop_ratio": footer_ratio,
        "header_crop_pt": header_crop,
        "footer_crop_pt": footer_crop,
        "cropped_width_pt": width,
        "cropped_height_pt": new_top - new_bottom,
    }


def load_pdf_renderer() -> Any:
    try:
        import pypdfium2 as pdfium
    except ImportError as exc:
        raise GeneMANIAError(
            "Generating report.png requires the optional dependency 'pypdfium2'. "
            "Install it with: python -m pip install pypdfium2"
        ) from exc
    return pdfium


def render_pdf_to_png(input_pdf: Path, output_png: Path, *, dpi: int) -> dict[str, Any]:
    pdfium = load_pdf_renderer()
    scale = dpi / 72.0
    document = pdfium.PdfDocument(str(input_pdf))
    try:
        page = document[0]
        bitmap = page.render(scale=scale)
        pil_image = bitmap.to_pil()
        try:
            output_png.parent.mkdir(parents=True, exist_ok=True)
            pil_image.save(output_png, format="PNG")
            return {
                "dpi": dpi,
                "renderer": "pypdfium2",
                "scale": scale,
                "width_px": pil_image.size[0],
                "height_px": pil_image.size[1],
            }
        finally:
            pil_image.close()
            close_bitmap = getattr(bitmap, "close", None)
            if callable(close_bitmap):
                close_bitmap()
    finally:
        close_document = getattr(document, "close", None)
        if callable(close_document):
            close_document()


def collect_web_report(
    *,
    genes: list[str],
    organism_id: str,
    layout: str,
    top_functions: int,
    browser: str,
    raw_pdf_path: Path,
    network_png_path: Path | None,
) -> dict[str, Any]:
    url = build_query_url(organism_id, genes)
    launch_kwargs: dict[str, Any] = {"headless": True}
    executable_path = resolve_browser_executable(browser)
    if executable_path:
        launch_kwargs["executable_path"] = executable_path

    try:
        with sync_playwright() as playwright:
            browser_obj = playwright.chromium.launch(**launch_kwargs)
            context = browser_obj.new_context(
                accept_downloads=True,
                viewport={"width": DEFAULT_VIEWPORT_WIDTH, "height": DEFAULT_VIEWPORT_HEIGHT},
                device_scale_factor=DEFAULT_DEVICE_SCALE_FACTOR,
            )
            page = context.new_page()
            page.goto(url, wait_until="networkidle", timeout=120000)
            page.wait_for_function(
                "typeof Query !== 'undefined' && Query.current && Query.current.result && typeof cy !== 'undefined' && cy && typeof cy.nodes === 'function' && cy.nodes().length > 0",
                timeout=120000,
            )

            metadata = page.evaluate(
                """async ({topFunctions, layout}) => {
                    const r = Query.current.result;
                    const deadline = Date.now() + 120000;
                    while ((r.searching || !r.resultOntologyCategories || r.resultOntologyCategories.length === 0) && Date.now() < deadline) {
                        await new Promise(resolve => setTimeout(resolve, 500));
                    }
                    if (!r.resultOntologyCategories || r.resultOntologyCategories.length === 0) {
                        throw new Error("GeneMANIA page loaded but ontology categories never became available.");
                    }

                    const current = [...r.coloringFunctions];
                    current.forEach(item => r.removeFunctionColoring(item));

                    const selected = r.resultOntologyCategories.slice(0, topFunctions);
                    selected.forEach(item => r.addFunctionColoring(item));

                    await new Promise(resolve => {
                        let done = false;
                        const finish = () => {
                            if (!done) {
                                done = true;
                                resolve();
                            }
                        };
                        const timer = setTimeout(finish, 12000);
                        if (typeof cy !== 'undefined' && cy && typeof cy.one === 'function') {
                            cy.one('layoutstop', () => {
                                clearTimeout(timer);
                                finish();
                            });
                        }
                        if (layout === 'circle') {
                            r.circleLayout();
                        } else if (layout === 'linear') {
                            r.linearLayout();
                        } else {
                            r.forceLayout();
                        }
                    });

                    r.fitGraph();
                    await new Promise(resolve => setTimeout(resolve, 1000));

                    return {
                        title: document.title,
                        finalUrl: window.location.href,
                        nodeCount: cy.nodes().length,
                        edgeCount: cy.edges().length,
                        selectedFunctions: r.coloringFunctions.map(item => ({
                            id: item.id,
                            description: item.ontologyCategory.description,
                            qValue: item.qValue,
                            color: item.color,
                            coverage: item.coverageFormatted
                        })),
                        networkGroups: r.resultAllGroups.map(group => ({
                            name: group.ele.name,
                            color: group.color
                        }))
                    };
                }""",
                {"topFunctions": top_functions, "layout": layout},
            )

            if network_png_path is not None:
                data_url = page.evaluate(
                    """scale => cy.png({
                        full: true,
                        scale: scale,
                        bg: '#ffffff'
                    })""",
                    DEFAULT_NETWORK_PNG_SCALE,
                )
                marker = "base64,"
                if marker not in data_url:
                    raise GeneMANIAError("Unexpected network PNG data returned by GeneMANIA.")
                network_png_path.parent.mkdir(parents=True, exist_ok=True)
                network_png_path.write_bytes(base64.b64decode(data_url.split(marker, 1)[1]))

            with page.expect_download(timeout=120000) as download_info:
                page.evaluate("Query.current.result.report()")
            download = download_info.value
            raw_pdf_path.parent.mkdir(parents=True, exist_ok=True)
            download.save_as(str(raw_pdf_path))
            browser_obj.close()
    except PlaywrightError as exc:
        raise GeneMANIAError(f"GeneMANIA browser automation failed: {exc}") from exc

    metadata["requestedUrl"] = url
    metadata["layout"] = layout
    metadata["topFunctionsRequested"] = top_functions
    return metadata


def build_summary_payload(
    *,
    genes: list[str],
    args: Any,
    layout: dict[str, Path | str | None],
    input_artifacts: dict[str, str],
    protocol_payload: dict[str, Any],
    report_metadata: dict[str, Any],
    crop_metadata: dict[str, Any],
    png_metadata: dict[str, Any],
) -> dict[str, Any]:
    return {
        "_meta": {
            "task": TASK_METADATA,
            "query_genes": genes,
            "query_count": 1,
            "organism_id": args.organism_id,
            "layout": args.layout,
            "top_functions_requested": args.top_functions,
            "png_dpi": args.png_dpi,
            "output_mode": layout["mode"],
            "job_dir": str(layout["job_dir"]) if isinstance(layout["job_dir"], Path) else "",
            "temp_dir": str(layout["temp_dir"]) if isinstance(layout["temp_dir"], Path) else "",
            "report_pdf_path": str(layout["report_pdf_path"]),
            "report_png_path": str(layout["report_png_path"]),
            "summary_path": str(layout["summary_path"]),
            "input_artifacts": input_artifacts,
            "protocol_check_file": str(args.protocol_check_file),
            "protocol_check": protocol_payload,
            "crop": crop_metadata,
            "png_render": png_metadata,
        },
        "result": {
            "title": report_metadata.get("title", ""),
            "requested_url": report_metadata.get("requestedUrl", ""),
            "final_url": report_metadata.get("finalUrl", ""),
            "node_count": report_metadata.get("nodeCount", 0),
            "edge_count": report_metadata.get("edgeCount", 0),
            "selected_function_count": len(report_metadata.get("selectedFunctions", [])),
            "selected_functions": report_metadata.get("selectedFunctions", []),
            "network_groups": report_metadata.get("networkGroups", []),
        },
    }


def write_error_payload(
    *,
    path: Path,
    message: str,
    stage: str,
    temp_dir: Path | None,
    raw_report_pdf: Path | None,
    raw_network_png: Path | None,
) -> None:
    payload = {
        "stage": stage,
        "error": message,
        "temp_dir": str(temp_dir) if temp_dir else "",
        "raw_report_pdf": str(raw_report_pdf) if raw_report_pdf and raw_report_pdf.exists() else "",
        "raw_network_png": str(raw_network_png) if raw_network_png and raw_network_png.exists() else "",
    }
    write_json(path, payload)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    genes = load_genes(args)
    if not genes:
        print("No gene inputs were provided.", file=sys.stderr)
        return 2
    if args.top_functions < 1:
        print("--top-functions must be at least 1.", file=sys.stderr)
        return 2
    if args.png_dpi < 72:
        print("--png-dpi must be at least 72.", file=sys.stderr)
        return 2

    try:
        layout = build_output_layout(args=args, genes=genes)
    except GeneMANIAError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    if args.protocol_check_file is None:
        print(
            "Formal task execution requires --protocol-check-file. Generate it first via scripts/protocol_gate.py.",
            file=sys.stderr,
        )
        return 2

    try:
        protocol_payload = validate_protocol_ticket(
            args.protocol_check_file,
            page_key=PAGE_KEY,
            task_key=TASK_KEY,
            input_type=infer_input_type(query_count=1, input_file=None),
            job_dir=layout["job_dir"] if isinstance(layout["job_dir"], Path) else None,
        )
    except ProtocolGateError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    temp_dir = layout["temp_dir"] if isinstance(layout["temp_dir"], Path) else None
    if temp_dir is not None and args.protocol_check_file.exists() and isinstance(layout["job_dir"], Path):
        if args.protocol_check_file.parent == layout["job_dir"]:
            temp_dir.mkdir(parents=True, exist_ok=True)
            relocated_protocol = temp_dir / args.protocol_check_file.name
            if relocated_protocol.exists():
                relocated_protocol.unlink()
            shutil.move(str(args.protocol_check_file), str(relocated_protocol))
            args.protocol_check_file = relocated_protocol
    input_artifacts = copy_input_artifacts(genes=genes, temp_dir=temp_dir)
    raw_report_pdf = Path(input_artifacts["raw_report_pdf"]) if input_artifacts["raw_report_pdf"] else None
    raw_network_png = Path(input_artifacts["raw_network_png"]) if input_artifacts["raw_network_png"] else None
    raw_pdf_path = raw_report_pdf if raw_report_pdf is not None else Path(str(layout["report_pdf_path"]) + ".raw")

    report_pdf_path = layout["report_pdf_path"]
    report_png_path = layout["report_png_path"]
    summary_path = layout["summary_path"]
    errors_path = layout["errors_path"]
    assert isinstance(report_pdf_path, Path)
    assert isinstance(report_png_path, Path)
    assert isinstance(summary_path, Path)
    assert isinstance(errors_path, Path)

    try:
        report_metadata = collect_web_report(
            genes=genes,
            organism_id=args.organism_id,
            layout=args.layout,
            top_functions=args.top_functions,
            browser=args.browser,
            raw_pdf_path=raw_pdf_path,
            network_png_path=raw_network_png,
        )
        crop_metadata = crop_pdf_first_page(raw_pdf_path, report_pdf_path)
        png_metadata = render_pdf_to_png(report_pdf_path, report_png_path, dpi=args.png_dpi)
        write_json(
            summary_path,
            build_summary_payload(
                genes=genes,
                args=args,
                layout=layout,
                input_artifacts=input_artifacts,
                protocol_payload=protocol_payload,
                report_metadata=report_metadata,
                crop_metadata=crop_metadata,
                png_metadata=png_metadata,
            ),
        )
    except GeneMANIAError as exc:
        write_error_payload(
            path=errors_path,
            message=str(exc),
            stage="task_execution",
            temp_dir=temp_dir,
            raw_report_pdf=raw_report_pdf,
            raw_network_png=raw_network_png,
        )
        print(str(exc), file=sys.stderr)
        return 1

    if raw_report_pdf is not None and raw_report_pdf.exists():
        raw_report_pdf.unlink()
    if raw_network_png is not None and raw_network_png.exists():
        raw_network_png.unlink()

    print(f"Report PDF: {report_pdf_path}", file=sys.stderr)
    print(f"Report PNG: {report_png_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
