#!/usr/bin/env python3
"""Join Gene-miRNA pair tables with miRNA-lncRNA query results."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Merge an upstream Gene-miRNA pairs CSV with one or more "
            "miRNA-lncRNA result CSVs and emit Gene-miRNA-lncRNA pair tables."
        )
    )
    parser.add_argument(
        "--pairs-csv",
        required=True,
        help="Upstream Gene-miRNA pairs CSV. Must contain a 'miRNA' column.",
    )
    parser.add_argument(
        "--lncbase-csv",
        help="Optional DIANA-LncBase v3 result CSV generated by mirna_to_lncrna.py.",
    )
    parser.add_argument(
        "--encori-csv",
        help="Optional ENCORI result CSV generated by mirna_to_lncrna.py.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory. Top level keeps only result CSVs; temp/ stores summary.json.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def normalize_value(value: str | None) -> str:
    return (value or "").strip()


def index_method_rows(
    rows: list[dict[str, str]],
    *,
    method_name: str,
    query_key: str,
    result_key: str | None,
) -> dict[str, list[dict[str, str]]]:
    indexed: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        query_value = normalize_value(row.get(query_key))
        result_value = normalize_value(row.get(result_key)) if result_key else ""
        candidates = sorted({value for value in (query_value, result_value) if value})
        for mirna in candidates:
            indexed.setdefault(mirna, []).append(row)
    if not indexed:
        raise ValueError(f"No miRNA keys found in {method_name} result file.")
    return indexed


def merge_rows(
    pair_rows: list[dict[str, str]],
    method_rows: dict[str, list[dict[str, str]]],
    *,
    source_method: str,
    method_prefix: str,
) -> tuple[list[str], list[dict[str, str]], dict[str, int]]:
    pair_fieldnames = list(pair_rows[0].keys()) if pair_rows else []
    sample_method_rows = next(iter(method_rows.values()))
    method_fieldnames = list(sample_method_rows[0].keys()) if sample_method_rows else []

    output_fieldnames = pair_fieldnames + ["source_method"] + [
        f"{method_prefix}_{name}" for name in method_fieldnames
    ]
    merged_rows: list[dict[str, str]] = []
    unmatched_pairs = 0

    for pair in pair_rows:
        mirna = normalize_value(pair.get("miRNA"))
        matches = method_rows.get(mirna, [])
        if not matches:
            unmatched_pairs += 1
            continue
        for method_row in matches:
            merged_row = dict(pair)
            merged_row["source_method"] = source_method
            for name in method_fieldnames:
                merged_row[f"{method_prefix}_{name}"] = method_row.get(name, "")
            merged_rows.append(merged_row)

    summary = {
        "input_pair_count": len(pair_rows),
        "matched_pair_count": len({(row.get('Gene', ''), row.get('miRNA', '')) for row in merged_rows}),
        "output_row_count": len(merged_rows),
        "unmatched_pair_count": unmatched_pairs,
    }
    return output_fieldnames, merged_rows, summary


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()
    pairs_path = Path(args.pairs_csv).resolve()
    output_dir = Path(args.output_dir).resolve()
    temp_dir = output_dir / "temp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    pair_rows = read_csv_rows(pairs_path)
    if not pair_rows:
        raise SystemExit("Pairs CSV is empty.")
    if "miRNA" not in pair_rows[0]:
        raise SystemExit("Pairs CSV must contain a 'miRNA' column.")

    summary_payload: dict[str, object] = {
        "pairs_csv": str(pairs_path),
        "pair_row_count": len(pair_rows),
        "outputs": {},
    }

    if args.lncbase_csv:
        lncbase_path = Path(args.lncbase_csv).resolve()
        lncbase_rows = read_csv_rows(lncbase_path)
        lncbase_index = index_method_rows(
            lncbase_rows,
            method_name="LncBaseV3",
            query_key="query_mirna",
            result_key="result_mirna",
        )
        fieldnames, merged_rows, merge_summary = merge_rows(
            pair_rows,
            lncbase_index,
            source_method="LncBaseV3",
            method_prefix="lncbasev3",
        )
        output_path = output_dir / "gene_mirna_lncrna_pairs_lncbasev3.csv"
        write_csv(output_path, fieldnames, merged_rows)
        summary_payload["outputs"] = {
            **summary_payload["outputs"],
            "lncbasev3": {
                "input_result_csv": str(lncbase_path),
                "output_csv": str(output_path),
                **merge_summary,
            },
        }

    if args.encori_csv:
        encori_path = Path(args.encori_csv).resolve()
        encori_rows = read_csv_rows(encori_path)
        encori_index = index_method_rows(
            encori_rows,
            method_name="ENCORI",
            query_key="query_mirna",
            result_key="miRNAname",
        )
        fieldnames, merged_rows, merge_summary = merge_rows(
            pair_rows,
            encori_index,
            source_method="ENCORI",
            method_prefix="encori",
        )
        output_path = output_dir / "gene_mirna_lncrna_pairs_encori.csv"
        write_csv(output_path, fieldnames, merged_rows)
        summary_payload["outputs"] = {
            **summary_payload["outputs"],
            "encori": {
                "input_result_csv": str(encori_path),
                "output_csv": str(output_path),
                **merge_summary,
            },
        }

    if not summary_payload["outputs"]:
        raise SystemExit("Provide --lncbase-csv and/or --encori-csv.")

    summary_path = temp_dir / "summary.json"
    summary_path.write_text(json.dumps(summary_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
